using System;
using System.Collections.Generic;
using System.Text;

namespace FlightManagementSystem.Models
{
    public class Flight
    {
        public int flightId { get; set; }           // Unique ID for each scheduled flight
        public string flightCode { get; set; }      // Airline flight code - generated by system  
        public int aircraftId { get; set; }         // ID of the aircraft assigned to this flight 
        public int pilotId { get; set; }            // ID of the pilot assigned to this flight
        public string origin { get; set; }          // Departure airport / city
        public string destination { get; set; }     // Arrival airport / city
        public string departureDate { get; set; }   // Scheduled departure date
        public string departureTime { get; set; }   // Scheduled departure time
        public decimal ticketPrice { get; set; }    // Price per seat for this flight
        public int availableSeats { get; set; }     // Number of seats still open 
        public string status { get; set; }          // Flight status: Scheduled | Departed | Cancelled
        public int flightDurationHours { get; set; }// needed to update Pilot.flightHours when the flight departs
    }
}
